In [1]:
import cv2
import numpy
import os
import matplotlib.pyplot as plt

In [2]:
path = "/home/yalamaku/Documents/Thesis/Dataset_files/ZED_camera_dataset/Roboflow_annotated_data/RPTU-university-Data/train/train_semantic_segmentation_masks"

images = [os.path.join(path, image) for image in os.listdir(path)]


#mask = cv2.imread("/home/yalamaku/Documents/Detectron_2/Dataset/ZED_cam_data/annotations/panoptic_segmentation_annotations_2/semantic_masks/886.png")

In [3]:
for image in images:
    #print(image)
    img = cv2.imread(image)
    print(image.split('/')[-1])
    print(numpy.unique(img))

182.png
[0 1 2 5 6 8]
467.png
[0 1 2 5 6 8]
511.png
[ 0  1  2  5  8 10]
137.png
[0 1 2 5 8]
12.png
[0 1 2 5 6 8 9]
747.png
[0 1 2 5 6 7 8]
709.png
[0 1 2 4 5 6 7 8]
268.png
[0 1 2 5 6 8]
1053.png
[0 1 2 5 6 8 9]
781.png
[0 1 2 5 6 8]
851.png
[0 1 2 5 6 9]
135.png
[0 1 2 5 6 8 9]
55.png
[0 1 2 5 6]
876.png
[0 1 2 5 6 8]
425.png
[0 1 2 5 6 7 8]
1109.png
[0 1 2 5 6 8]
221.png
[0 1 2 5 8]
446.png
[0 1 2 5 6 9]
109.png
[0 1 2 5 6 8 9]
976.png
[0 1 2 5 6 8]
635.png
[0 1 2 5 6 8]
397.png
[0 1 2 5 7 8]
75.png
[0 1 2 5 6 7 8 9]
238.png
[0 1 2 5 6 8]
826.png
[ 0  1  2  5  6  7 10]
518.png
[0 1 2 5 6 9]
749.png
[0 1 2 5 6 7]
1069.png
[0 1 2 5 9]
347.png
[0 1 2 5 6 7 8]
592.png
[0 1 2 5 6 7 8 9]
16.png
[0 1 2 5 6 7]
849.png
[0 1 2 5 6 7 8 9]
263.png
[0 1 2 5 6 9]
142.png
[0 1 2 5 6 7 8 9]
161.png
[0 1 2 4 5 6 8 9]
469.png
[0 1 2 5 6 8 9]
858.png
[0 1 2 5 6 9]
367.png
[0 1 2 5 6 7]
773.png
[0 1 2 5 6]
408.png
[0 1 2 5 6 7 8 9]
639.png
[0 1 2 5 6 8]
126.png
[0 1 2 4 5 6 8 9]
752.png
[0 1 2 4 5 6 9]
